# Basic
title: ᴮᵒᵇ
# subtitle: ᴮᵒᵇ
description: Fear springs from ignorance!
# 头像里面的标题
avatarTitle: ᴮᵒᵇ
# 头像里面的描述
avatarDesc: 人丑多读书
#url: "http://1step2hell.github.io"

# Comment
# comment:
    # disqus: ᴮᵒᵇ
    # duoshuo: ᴮᵒᵇ 


# Staticman comments (full configuration in staticman.yml)
staticman:
  repository             : "1step2hell/1step2hell.github.io"
  url                    : "https://1step2hell.github.io"
  branch                 : "master"

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
  secret: "PznnZGu3P6eTHRPLORniSq+J61YEf+A9zmColXDM5icqF49gbunH51B8+h+i2IvewpuxtA9TFoK68TuhUp/X3YKmmqhXasegHYabY50fqF9nJh9npWNhvITdkQHeaOqnFXUIwxfiEeUt49Yoa2waRR7a5LdRAP3SVM8hz0KIBT4="

# Social
social:
    # weibo: 0000000 
    github: 1step2hell
    # twitter: 
    mail: 40080007@qq.com

# 百度统计 
# baidu:
#     id: 00000000000000000000  

# Google Analytics
# ga:
#    id: UA-00000000000
#    host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


